[build]
command = "npm install"
publish = ".next"
functions = "functions"

{
  "builds": [
    {
      "src": "packages/**/*",
      "useGitIgnore": true,
      "builds": [
        {
          "id": "nextjs",
          "src": "packages/**/*",
          "useGitIgnore": true,
          "command": "CI= npm run build",
          "publish": ".next"
        }
      ]
    }
  ]
}



[[plugins]]
  package = "@netlify/plugin-nextjs"



[dev] 
functions = "functions"

[functions] 
directory = "functions"

